// Generated by gencpp from file open_manipulator_msgs/GetJointPose.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_GETJOINTPOSE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_GETJOINTPOSE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/GetJointPoseRequest.h>
#include <open_manipulator_msgs/GetJointPoseResponse.h>


namespace open_manipulator_msgs
{

struct GetJointPose
{

typedef GetJointPoseRequest Request;
typedef GetJointPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointPose
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::GetJointPose > {
  static const char* value()
  {
    return "d90103d910754a636e20bdfefafe3642";
  }

  static const char* value(const ::open_manipulator_msgs::GetJointPose&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::GetJointPose > {
  static const char* value()
  {
    return "open_manipulator_msgs/GetJointPose";
  }

  static const char* value(const ::open_manipulator_msgs::GetJointPose&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::GetJointPoseRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::GetJointPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::GetJointPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::GetJointPoseRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::GetJointPose >
template<>
struct DataType< ::open_manipulator_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::GetJointPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::GetJointPoseResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::GetJointPose >
template<>
struct MD5Sum< ::open_manipulator_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::GetJointPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::GetJointPoseResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::GetJointPose >
template<>
struct DataType< ::open_manipulator_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::GetJointPose >::value();
  }
  static const char* value(const ::open_manipulator_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_GETJOINTPOSE_H
