(cl:defpackage open_manipulator_msgs-srv
  (:use )
  (:export
   "GETJOINTPOSE"
   "<GETJOINTPOSE-REQUEST>"
   "GETJOINTPOSE-REQUEST"
   "<GETJOINTPOSE-RESPONSE>"
   "GETJOINTPOSE-RESPONSE"
   "GETKINEMATICSPOSE"
   "<GETKINEMATICSPOSE-REQUEST>"
   "GETKINEMATICSPOSE-REQUEST"
   "<GETKINEMATICSPOSE-RESPONSE>"
   "GETKINEMATICSPOSE-RESPONSE"
  ))

